repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.1"
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: cargo fmt
        name: cargo fmt
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        pass_filenames: false
