[package]
name = "statustracker-server"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "^0.6.2"
mongodb = "^2.5.0"
reqwest = { version = "^0.11.18", features = ["json"] }
url = { version = "^2.3.1", features = ["serde"] }
smol_str = {version = "^0.2.0", features = ["serde"] }
uuid = { version = "^1.3.3", features = ["serde"] }
rocket = { version = "^0.5.0-rc.3", features = ["msgpack"] }
tokio = { version = "^1.28.1", features = ["full"] }
futures = "^0.3.28"
serde = "^1.0.163"
serde_json = "^1.0.96"
toml = "^0.7.4"
rmp-serde = "^1.1.1"
itertools = "^0.10.5"
tracing = "^0.1.37"
tracing-subscriber = { version = "^0.3.17", features = ["env-filter"] }
once_cell = "^1.17.1"
dotenvy = "^0.15.7"
