[package]
name = "statustracker-server"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "^0.6.8"
mongodb = "^2.3.1"
reqwest = { version = "^0.11.12", features = ["json"] }
smol_str = "^0.1.23"
uuid = "^1.2.1"
rocket = { version = "^0.5.0-rc.2", features = ["msgpack", "json"] }
tokio = { version = "^1.21.2", features = ["full"] }
futures = "^0.3.25"
serde = "^1.0.147"
serde_json = "^1.0.87"
rmp-serde = "^1.1.1"
itertools = "^0.10.5"
tracing = "^0.1.37"
once_cell = "^1.16.0"
