[package]
name = "statustracker-server"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "^0.6.2"
mongodb = "^2.3.1"
reqwest = { version = "^0.11.12", features = ["json"] }
url = { version = "^2.3.1", features = ["serde"] }
smol_str = "^0.1.23"
uuid = { version = "^1.2.1", features = ["serde"] }
rocket = { version = "^0.5.0-rc.2", features = ["msgpack"] }
tokio = { version = "^1.21.2", features = ["full"] }
futures = "^0.3.25"
serde = "^1.0.147"
serde_json = "^1.0.87"
toml = "^0.5.9"
rmp-serde = "^1.1.1"
itertools = "^0.10.5"
tracing = "^0.1.37"
tracing-subscriber = { version = "^0.3.16", features = ["env-filter"] }
once_cell = "^1.16.0"
dotenvy = "^0.15.6"
