env:
  browser: true
  es2022: true
extends:
  [
    eslint:recommended,
    plugin:@typescript-eslint/recommended,
    plugin:svelte/prettier,
  ]
overrides:
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ["tsconfig.json"]
  extraFileExtensions: [".svelte"]
plugins: ["@typescript-eslint", svelte]
rules: {}
