on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Exe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        run: rustup toolchain install nightly; rustup default nightly
      - name: Install musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Install musl tools
        run: sudo apt-get update; sudo apt-get install musl-tools
      - name: Build
        run: cargo +nightly build --release --target x86_64-unknown-linux-musl
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/statustracker-server
          asset_name: statustracker2-ubuntu-musl
          tag: ${{ github.ref }}
        if: ${{ github.event.action != 'workflow_dispatch' }}
