on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: Build
        run: cargo +nightly build --release
      - uses: actions/upload-artifact@v3
        with:
          name: server
          path: target/release/statustracker-server
