on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Exe
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: statustracker-server
            asset_name: statustracker2-ubuntu
          - os: windows-latest
            artifact_name: statustracker-server.exe
            asset_name: statustracker2-windows.exe
          - os: macos-latest
            artifact_name: statustracker-server
            asset_name: statustracker2-macos

    steps:
      - uses: actions/checkout@v3
      - name: Install nightly
        run: rustup toolchain install nightly; rustup default nightly
      - name: Build
        run: cargo +nightly build --release
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
        if: ${{ github.event.action != 'workflow_dispatch' }}
